build.gradle

test commit

---

src/main/java/qp/official/qp/domain/Question.java

1. Question @Builder.Default 추가

[refactor] Question @Builder.Default 추가

---

src/main/java/qp/official/qp/config/SecretSetting.java
src/main/resources/application.yml

민감 정보 (데이터베이스 정보)를 숨기는 코드 작성
```java
@Configuration
@PropertySources({
@PropertySource(value = "classpath:secrets.properties", ignoreResourceNotFound = true),
})
public class SecretSetting {
}
```
```yaml
DB_URL=~~
DB_USERNAME=~~
DB_PASSWORD=~~
```

[chore] 민감정보 숨기기

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

1. CICD Testing workflow 작성
2. CICD deploy workflow 작성
- CICD deploy workflow 작성

[chore] CICD Testing workflow 작성

---

.gitignore
Dockerfile

[chore] dockerfile 작성

---

.github/workflows/deploy.yml

[fix] CICD deploy build 되게 끔 수정

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/enums/Role.java
src/main/java/qp/official/qp/web/controller/UserRestController.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

- UserRestController 시그니처 생성
- UserConverter 작성
- UserRequestDTO, UserResponseDTO 작성

[feat] User api 시그니처 생성

---

src/main/java/qp/official/qp/web/controller/ImageController.java
src/main/java/qp/official/qp/web/dto/ImageResponseDTO.java

- 이미지 등록 시그니쳐 구현
- 이미지 삭제 시그니쳐 구현

[feat] 이미지 등록, 삭제 시그니쳐 구현

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/domain/enums/UserStatus.java
src/main/java/qp/official/qp/repository/UserRepository.java
src/main/java/qp/official/qp/service/UserService.java
src/main/java/qp/official/qp/service/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/UserRestController.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

- 회원 정보 조회 및 수정
- status enums ACTIVE로 변경

[feat] 회원 정보 조회 및 수정 기능

---

src/main/java/qp/official/qp/converter/AnswerConverter.java
src/main/java/qp/official/qp/domain/Answer.java
src/main/java/qp/official/qp/repository/AnswerRepository.java
src/main/java/qp/official/qp/service/AnswerCommandService.java
src/main/java/qp/official/qp/service/AnswerCommandServiceImpl.java
src/main/java/qp/official/qp/service/AnswerQueryService.java
src/main/java/qp/official/qp/service/AnswerQueryServiceImpl.java
src/main/java/qp/official/qp/web/controller/AnswerRestController.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java

- 작업사항 1
답변 도메인 시그니쳐 작성
- 작업사항 1
답변 작성 API 기능구현

[feat] 답변 도메인 시그니쳐 작성 및 답변 작성 API 기능구현

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/service/UserService.java
src/main/java/qp/official/qp/service/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/UserRestController.java

```java
User newUser = User.builder()
.name("Test_Name")
.email("Test_Email")
.point(0L)
.lastLogin(LocalDateTime.now())
.profileImage("https://www.notion.so/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fe29b9403-b3ec-44bc-8253-1cf1ad90d216%2Fb6d5f75a-3365-4d41-b12c-01cdf95b2985%2FUntitled.png?table=block&id=ea6c2693-588c-4707-b478-fac2c4cab6b9&spaceId=e29b9403-b3ec-44bc-8253-1cf1ad90d216&width=2000&userId=2d84c7f9-2777-4bd6-aa0b-c963f16a6468&cache=v2")
.role(Role.USER)
.nickname("testNickName")
.gender(Gender.DEFAULT)
.build();
```
- Test User 생성 코드 구현

[feat] 테스트 유저 생성 기능 구현

---

src/main/java/qp/official/qp/converter/HashtagConverter.java
src/main/java/qp/official/qp/converter/QuestionConverter.java
src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/repository/AnswerRepository.java
src/main/java/qp/official/qp/repository/QuestionRepository.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
src/main/java/qp/official/qp/web/controller/QuestionController.java
src/main/java/qp/official/qp/web/dto/HashtagResponseDTO.java
src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

- 전체 질문 페이징 조회 구현
- Question answers 양방향 연관관계 매핑
- HashtagResponse는 HashtagReturnDTO 으로 통일
- AnswerRepository 에서 Question 의 전문가 답변 갯수 조회 메서드 정의

[feat] 전체 질문 페이징 조회

---

src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/repository/QuestionRepository.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
src/main/java/qp/official/qp/web/controller/QuestionController.java

- Question 페이징 조회에 검색 기능 추가
- 특정 Question 조회시 조회수 증가 로직 추가

[feat] Question 페이징 조회에 검색 기능 추가

---

Dockerfile
src/main/java/qp/official/qp/QpBackendApplication.java

- Docker 컨테이너 안 TimeZone설정
- Dockerfile 작은 Base이미지 (openjdk:11-jre-slim) 설정

[fix] Docker 컨테이너 안 TimeZone설정

---

src/main/java/qp/official/qp/converter/AnswerConverter.java
src/main/java/qp/official/qp/repository/AnswerRepository.java
src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java

- 작업사항 1 : 특정 질문의 부모 답변 페이징 조회 시 응답에 null 포함되는 오류 수정

[fix] 특정 질문의 부모 답변 페이징 조회 시 응답에 null 포함되는 오류 수정

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/converter/QuestionReportConverter.java
src/main/java/qp/official/qp/domain/mapping/QuestionReport.java
src/main/java/qp/official/qp/repository/AnswerReportRepository.java
src/main/java/qp/official/qp/repository/QuestionReportRepository.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportCommandService.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportQueryService.java
src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportCommandService.java
src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportCommandServiceImpl.java
src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportQueryService.java
src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportQueryServiceImpl.java
src/main/java/qp/official/qp/validation/annotation/ExistQuestionReport.java
src/main/java/qp/official/qp/validation/validator/ExistQuestionReportValidator.java
src/main/java/qp/official/qp/web/controller/QuestionReportController.java
src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionReportResponseDTO.java

- 작업사항 1
질문 신고 작성 기능 구현
- 작업사항 2
질문 신고 조회 기능 구현
- 작업사항 1
질문에 대한 신고를 찾을 수 없는 경우에 대한 validation작성 추가

[feat] 질문 신고 및 질문 신고 조회 기능 구현

---

src/main/java/qp/official/qp/converter/AnswerConverter.java
src/main/java/qp/official/qp/domain/Answer.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
src/main/java/qp/official/qp/web/controller/AnswerRestController.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java

- 작업사항 1
답변 삭제 및 답변 수정 기능구현
- 작업사항 1
질문 수정 api의 request body에 userId 추가함에 따라 QuestionRequestDTO의 UpdateDTO메소드에 userId 추가

[feat] 답변 삭제 및 답변 수정 기능구현

---

src/main/java/qp/official/qp/repository/ImageRepository.java
src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
src/main/java/qp/official/qp/web/controller/ImageController.java

- 작업사항 1 : AWS S3 버킷 초기화 API 작성 -> qp 폴더 내 파일만 삭제되도록 구현

[feat] AWS S3 버킷 초기화 API 작성

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/converter/AnswerReportConverter.java
src/main/java/qp/official/qp/domain/mapping/AnswerReport.java
src/main/java/qp/official/qp/repository/AnswerReportRepository.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportCommandService.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportCommandServiceImpl.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportQueryService.java
src/main/java/qp/official/qp/service/AnswerReportService/AnswerReportQueryServiceImpl.java
src/main/java/qp/official/qp/validation/annotation/ExistAnswerReport.java
src/main/java/qp/official/qp/validation/validator/ExistAnswerReportValidator.java
src/main/java/qp/official/qp/web/controller/AnswerReportController.java
src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerReportResponseDTO.java

- 작업사항 1
답변 신고 작성 기능 구현
- 작업사항 2
답변 신고 조회 기능 구현
- 작업사항 1
찾고있는 답변 신고가 없는 경우에 대한 validation 추가

[feat] 답변 신고 작성 및 답변 신고 조회 기능 구현

---

src/main/java/qp/official/qp/converter/AnswerConverter.java
src/main/java/qp/official/qp/converter/AnswerLikesConverter.java
src/main/java/qp/official/qp/domain/Answer.java
src/main/java/qp/official/qp/domain/enums/AnswerLikeStatus.java
src/main/java/qp/official/qp/repository/AnswerLikesRepository.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
src/main/java/qp/official/qp/web/controller/AnswerRestController.java
src/main/java/qp/official/qp/web/dto/AnswerLikeRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerLikeResponseDTO.java
src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java

- 작업사항 1 : 답변 좋아요 기능 추가 (눌렀던 답변에 다시 좋아요 누르면 삭제되도록)
- 작업사항 2 : 답변 `response`에 `likeCount` 포함

[feat] 답변 좋아요 기능 구현

---

.github/workflows/deploy.yml
EnvBash.sh
build.gradle
src/main/java/qp/official/qp/config/SecretConfig.java

- CI/CD시 환경변수 설정 변경
- JWT secretKey 설정 변경
- Test 로깅 설정

[Chore] CI/CD시 환경변수 설정 변경

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/apiPayload/exception/handler/TokenHandler.java
src/main/java/qp/official/qp/config/SecretConfig.java
src/main/java/qp/official/qp/repository/UserRepository.java
src/main/java/qp/official/qp/service/TokenService/TokenService.java
src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
src/main/java/qp/official/qp/service/UserService.java
src/main/java/qp/official/qp/service/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/TokenController.java

[refactor] jwt 만료 시간 변경 및 isValidToken refactoring

---

src/main/java/qp/official/qp/service/TokenService/TokenService.java
src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
src/main/java/qp/official/qp/web/controller/TokenController.java

isValidToken을 통해 유효성 검사 후 갱신까지 하는 메서드 추가
- isValidToken에서 user 체크하고 유효성 검사하도록 수정
- checkValidAndRenew메서드 생성 (isValidToken에서 토큰 갱신하는 기능 더해진 메서드)

[refactor] isValidToken 문제 수정 

---

src/main/java/qp/official/qp/web/controller/AnswerReportController.java
src/main/java/qp/official/qp/web/controller/AnswerRestController.java
src/main/java/qp/official/qp/web/controller/HashtagController.java
src/main/java/qp/official/qp/web/controller/ImageController.java
src/main/java/qp/official/qp/web/controller/QuestionController.java
src/main/java/qp/official/qp/web/controller/QuestionReportController.java
src/main/java/qp/official/qp/web/controller/UserRestController.java

[fix] CORS 해결

---

src/main/java/qp/official/qp/converter/TokenConverter.java
src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/service/TokenService/TokenService.java
src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
src/main/java/qp/official/qp/web/controller/AnswerController.java
src/main/java/qp/official/qp/web/controller/AnswerReportController.java
src/main/java/qp/official/qp/web/controller/UserRestController.java
src/main/java/qp/official/qp/web/dto/TokenDTO/AccessTokenDTO.java
src/main/java/qp/official/qp/web/dto/TokenDTO/RefreshTokenDTO.java
src/main/java/qp/official/qp/web/dto/TokenDTO/TokenResponseDTO.java

- AccessTokenDTO, RefreshTokenDTO를 이용해 캡슐화
- TokenConverter를 이용해 캡슐화
- isValid 로직 오류 수정
- User 의 setRefreshToken 수정
- 답변 신고 토큰 검증 로직 구현
- AnswerRestController -> AnswerController 클래스명 변경

[refactor] TokenService 리팩토링

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/repository/UserRepository.java
src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java

- 작업사항 1 : 잘못된 토큰 입력 시 500 에러 발생 -> 에러 핸들러 발생 하도록 수정
- 작업사항 2 : 이미 가입 된 회원 중복 가입 되는 오류 -> 기존 회원 정보 응답하도록 수정
- 작업사항 1 : `User` 엔티티 디플트 수정

[fix] 회원 가입 중 발생하는 오류 수정

---

src/main/java/qp/official/qp/web/controller/AnswerReportController.java
src/main/java/qp/official/qp/web/controller/QuestionReportController.java

- 작업사항 1 : 질문 신고, 답변 신고 Swagger 헤더 값 설정 추가

[refactor] 질문 신고, 답변 신고 Swagger 헤더 값 설정 추가

---

src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java

- 작업사항 1
답변, 답변신고, 질문 RequestDTO에 null로 들어오면 안되는 부분 수정

[fix] 답변, 답변신고, 질문 RequestDTO에 null로 들어오면 안되는 부분 수정

---

src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java

[fix] 해시태그 없을때 500에러 수정

---

src/main/java/qp/official/qp/validation/validator/ExistAnswerReportValidator.java
src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
src/main/java/qp/official/qp/validation/validator/ExistQuestionReportValidator.java
src/main/java/qp/official/qp/validation/validator/ExistQuestionValidator.java
src/main/java/qp/official/qp/validation/validator/ExistUserValidator.java
src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java

- 널일때 500 애러가 나던 커스텀 validator들 수정

[fix] 커스텀 Validator null check

---

src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java

- createQuestion 테스트 코드 구현
- QuestionHashtagConverter의 toQuestionHashtagList 를 이용해 QuestionCommandServiceImpl을 리팩토링 하였음

[feature] QuestionCommandServiceTest.createQuestion Test 구현

---

src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
src/main/java/qp/official/qp/domain/Hashtag.java
src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java

[refactor] QuestionHashtagConverter. Question, Hashtag 연관관계 편의 메서드 수정

---

src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java

- 작업사항 1
답변 작성시 UnexpectedTypeException 오류 해결

[fix] 답변 작성시 UnexpectedTypeException 오류 해결

---

src/main/java/qp/official/qp/domain/Answer.java
src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/test/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImplTest.java
src/test/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImplTest.java

- 작업사항 1 : AnswerCommandService 테스트 코드 작성
- 작업사항 2 : AnswerQueryService 테스트 코드 작성

[feat] 답변 서비스 테스트 코드 작성

---

src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
src/test/java/qp/official/qp/service/HashtagService/HashtagCommandServiceTest.java
src/test/java/qp/official/qp/service/HashtagService/HashtagQueryServiceTest.java

[test] 해시태그 서비스 테스트 코드 작성

---

src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java
src/test/java/qp/official/qp/service/QuestionService/QuestionQueryServiceTest.java

- 질문 커맨드 서비스 테스트 코드 작성
- 질문 쿼리 서비스 테스트 코드 작성

[test] 질문 서비스 테스트 코드 작성

---

src/main/java/qp/official/qp/QpBackendApplication.java
src/main/java/qp/official/qp/config/JpaEnversConfiguration.java
src/main/java/qp/official/qp/config/ObjectMapperConfig.java
src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/web/controller/QuestionController.java
src/test/java/qp/official/qp/web/controller/QuestionControllerTest.java

- QuestionController.createQuestion 테스트 코드 작성
- EnableJpaAuditing 어노테이션 이동 [관련 자료](https://velog.io/@twoone14/Spring-Junit-WebMvcTest-%EC%9D%98-JPA-metamodel-must-not-be-empty-%EC%97%90%EB%9F%AC)
- ObjectMapper 관련 한글 설정 [관련 자료](https://www.notion.so/Gson-c606b278aa414d68b9ff97ef85860a7f?pvs=4)

[test] QuestionController.createQuestion 테스트 코드 작성

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/validation/validator/ExistUserValidator.java
src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
src/test/java/qp/official/qp/validation/validator/ExistUserValidatorTest.java

- ExistUser 테스트 코드 작성
- ExistUser에서 userId가 null일때 false 반환하도록 로직 변경
- Request DTO에서 사용되는 ExistUser에서 NotNull 제거
- ErrorState USER_ID_NULL 추가

[test] ExistUser 테스트 코드 작성

---

src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java

- 작업사항 1
HashtagRequestDTO와 QuestionRequestDTO에 생성자 어노테이추가

[fix] HashtagRequestDTO와 QuestionRequestDTO에 생성자 어노테이추가

---

src/main/java/qp/official/qp/web/controller/QuestionController.java
src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java

- QuestionController에서 질문 수정, 삭제, 생성 시 유저 유효성 검사
- 질문 수정 안되는 문제 해결

[feature] 질문 생성, 수정, 삭제 시 유저 유효성 확인

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/validation/validator/ExistAnswerReportValidator.java
src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
src/main/java/qp/official/qp/validation/validator/ExistQuestionReportValidator.java
src/main/java/qp/official/qp/validation/validator/ExistQuestionValidator.java
src/test/java/qp/official/qp/validation/validator/ExistAnswerReportValidatorTest.java
src/test/java/qp/official/qp/validation/validator/ExistAnswerValidatorTest.java
src/test/java/qp/official/qp/validation/validator/ExistHashTagValidatorTest.java
src/test/java/qp/official/qp/validation/validator/ExistQuestionReportValidatorTest.java
src/test/java/qp/official/qp/validation/validator/ExistQuestionValidatorTest.java

[test] Validator 테스트 코드 작성

---

src/main/java/qp/official/qp/converter/AnswerConverter.java
src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java

- 작업사항 1 : 답변 조회 시 응답에 답변 작성한 사용자 명 추가

[refactor] 답변 조회 시 응답에 답변 작성한 사용자 명 추가

---

src/main/java/qp/official/qp/web/controller/UserController.java
src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
src/main/java/qp/official/qp/web/dto/ImageRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
src/test/java/qp/official/qp/web/controller/HashtagControllerTest.java
src/test/java/qp/official/qp/web/controller/ImageControllerTest.java
src/test/java/qp/official/qp/web/controller/UserControllerTest.java

- 작업사항 1 : 이미지, 유저, 해시태그 Controller 테스트 코드 작성
- 작업사항 2 : `UserRestController` 클래스를  `UserController`로 클래스 명 변경

[test] 이미지, 유저, 해시태그 Controller 테스트 코드 작성

---

src/main/java/qp/official/qp/domain/Answer.java
src/main/java/qp/official/qp/domain/Question.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/domain/mapping/QuestionHashTag.java
src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
src/test/java/qp/official/qp/repository/AnswerRepositoryTest.java
src/test/java/qp/official/qp/repository/QuestionRepositoryTest.java

- 모든 일대다 연관관계에서 1이 연관관계 관리하도록 변경

[refactor] 모든 일대다 연관관계에서 1이 연관관계 관리하도록 변경

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/UserController.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

- Test 유저 생성시 회원가입과 똑같은 반환값으로 만들기

[refactor] Test 유저 생성시 회원가입과 똑같은 반환값으로 만들기

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

- 작업사항 1
[refactor] 회원 정보 조회 시 response에 createdAt추가

[refactor] 회원 정보 조회 시 response에 createdAt추가

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/service/UserService/UserService.java
src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/UserController.java
src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

[feat] 포인트 충전 및 차감 API 구현

---

src/main/java/qp/official/qp/converter/QuestionConverter.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
src/main/java/qp/official/qp/web/controller/QuestionController.java
src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java

- 특정 질문 조회시 전문가 답변 갯수, 답변 갯수 같이 반환하도록 수정
- swagger에 childStatus 명세

[feat] 특정 질문 조회시 전문가 답변 갯수, 답변 갯수 같이 반환하도록 수정

---

src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/converter/QuestionConverter.java
src/main/java/qp/official/qp/repository/QuestionRepository.java
src/main/java/qp/official/qp/repository/UserQuestionAlarmRepository.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
src/main/java/qp/official/qp/web/controller/QuestionController.java
src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java

- 작업사항 1 : 내가 한 질문 정보 조회 API
- 작업사항 2 : 알림 설정한 질문 정보 조회 API

[feat] 내가 한 질문 및 알림 설정한 질문 정보 조회 API 구현

---

src/main/java/qp/official/qp/converter/UserConverter.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/service/UserService/UserService.java
src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
src/main/java/qp/official/qp/web/controller/UserController.java
src/main/java/qp/official/qp/web/dto/UserResponseDTO.java

[feat] User의 Role 변경 API 구현

---

build.gradle
src/main/java/qp/official/qp/QpBackendApplication.java
src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
src/main/java/qp/official/qp/apiPayload/code/status/SuccessStatus.java
src/main/java/qp/official/qp/apiPayload/exception/handler/ExpertHandler.java
src/main/java/qp/official/qp/converter/ExpertConverter.java
src/main/java/qp/official/qp/domain/Expert.java
src/main/java/qp/official/qp/domain/User.java
src/main/java/qp/official/qp/repository/ExpertRepository.java
src/main/java/qp/official/qp/scheduler/ExpertInitializer.java
src/main/java/qp/official/qp/service/ExpertService/ExpertCommandService.java
src/main/java/qp/official/qp/service/ExpertService/ExpertCommandServiceImpl.java
src/main/java/qp/official/qp/web/controller/ExpertController.java
src/main/java/qp/official/qp/web/dto/ExpertRequestDTO.java
src/main/java/qp/official/qp/web/dto/ExpertResponseDTO.java

[feat] 전문가 인증 기능 구현
